Changing Readme.md
davidbjourno/making-interactive-graphics pull request #1
Opened 2017-10-13 07:58 UTC by henryjameslau

Hi David, 
Enjoyed the journocoders session last night. My first one and really interesting to learn more about React. I've made some edits to the Readme from my experience of last night to hopefully make it easier (and put in that missing bracket).
Cheers Henry

2017-10-13 20:31 UTC, davidbjourno commented
Nice one, Henry. Reviewing now…

2017-10-13 20:35 UTC, davidbjourno approved these changes

2017-10-13 20:35 UTC, davidbjourno commented on README.md
> +}}
I think this would actually break App.js — the code block here refers only to `render()`, the class should already be closing.

2017-10-13 20:35 UTC, davidbjourno commented on README.md
> +And remove the line in Chart.js that specifies the fill of each '<rect>'
Good spot — could have sworn I'd updated this.

2017-10-13 20:37 UTC, davidbjourno requested changes

2017-10-13 20:37 UTC, davidbjourno commented on README.md
> +}}
Re-opening.

2017-10-13 20:44 UTC, davidbjourno requested changes

2017-10-13 20:44 UTC, davidbjourno commented on README.md
> +In his book [‘React + D3v4’](https://swizec.com/reactd3js/), Swizec Teller suggests abandoning the no-D3-DOM-control rule when it comes to rendering chart axes, and I'm inclined to agree with him. Ax
Quotes should be backticks.

2017-10-17 06:42 UTC, henryjameslau commented
Hi David, thanks for those suggestions. I've made those changes

2017-11-01 17:44 UTC, merged